// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBD.Tracker.DAL;

namespace NBD.Tracker.Migrations
{
    [DbContext(typeof(TrackerContext))]
    [Migration("20180716131715_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NBD.SDK.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsReached");

                    b.Property<Guid?>("ParentId");

                    b.Property<long>("Progress");

                    b.Property<int>("RecurrenceType");

                    b.Property<long>("RecurrenceValue");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int?>("Target");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("NBD.SDK.Goal", b =>
                {
                    b.HasOne("NBD.SDK.Goal", "Parent")
                        .WithMany("SubGoals")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
